from pathlib import Path
from .llm import LLMClient

class ProductFactory:
    def __init__(self, output_dir='generated_products'):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
        self.llm = LLMClient()

    def create(self, business, product, day):
        system = ('You are a product studio inside AI Earth. Create useful, original digital products. '
                  'Never claim real-world sales or credentials. Return a concise product brief and a deliverable in Markdown.')
        prompt = f'''Business: {business.name}\nSector: {business.sector}\nProduct type: {product.kind}\nProduct name: {product.name}\nQuality: {product.quality:.1f}\nCreate a practical version suitable for a first release. Include title, target user, promise, table of contents/sections, and the actual first-release content.'''
        result = self.llm.generate(system, prompt)
        if result.text:
            text = result.text
            source = result.provider
        else:
            text = self._fallback(business, product)
            source = 'template'
        path = self.output_dir / f'{business.id}_{product.id}_day{day}.md'
        path.write_text(f'# {product.name}\n\nGenerated by: {source}\n\n{text}\n', encoding='utf-8')
        return path, source

    def _fallback(self, b, p):
        return f'''## Product brief\nA first-release {p.kind} from {b.name}.\n\n## Target user\nA learner, creator, founder, or professional who wants a practical outcome in {b.sector.lower()}.\n\n## Release 1\n1. Problem and context\n2. Practical framework\n3. Worked example\n4. Action checklist\n5. Quality checklist\n\n## Next experiment\nCollect simulated customer feedback and improve the weakest section before the next release.'''
